<?php
$finder = PhpCsFixer\Finder::create()
    ->exclude([
        'Submodules',
    ])
    ->in(__DIR__.'/app')
    ->in(__DIR__.'/database')
    ->in(__DIR__.'/routes')
    ->in(__DIR__.'/tests');

$config = new PhpCsFixer\Config;

return $config
    ->setFinder($finder)
    ->setUsingCache(false)
    ->setRiskyAllowed(true)
    ->setRules([
        'align_multiline_comment' => ['comment_type' => 'phpdocs_only'],
        'array_indentation' => true,
        'array_push' => true,
        'array_syntax' => ['syntax' => 'short'],
        'assign_null_coalescing_to_coalesce_equal' => true,
        'attribute_empty_parentheses' => ['use_parentheses' => false],
        'backtick_to_shell_exec' => true,
        'binary_operator_spaces' => ['default' => 'single_space'],
        'blank_line_after_namespace' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => ['statements' => ['break', 'continue', 'declare', 'return', 'throw', 'try']],
        'blank_line_between_import_groups' => true,
        'blank_lines_before_namespace' => ['min_line_breaks' => 2, 'max_line_breaks' => 2],
        'braces_position' => [
            'allow_single_line_anonymous_functions' => true,
            'allow_single_line_empty_anonymous_classes' => true,
            'anonymous_classes_opening_brace' => 'same_line',
            'anonymous_functions_opening_brace' => 'same_line',
            'classes_opening_brace' => 'next_line_unless_newline_at_signature_end',
            'control_structures_opening_brace' => 'same_line',
            'functions_opening_brace' => 'next_line_unless_newline_at_signature_end',
        ],
        'cast_spaces' => ['space' => 'single'],
        'class_attributes_separation' => [
            'elements' => [
                'const' => 'one',
                'method' => 'one',
                'property' => 'one',
                'trait_import' => 'none',
                'case' => 'none',
            ],
        ],
        'class_definition' => [
            'inline_constructor_arguments' => false,
            'multi_line_extends_each_single_line' => false,
            'single_item_single_line' => false,
            'single_line' => false,
            'space_before_parenthesis' => true,
        ],
        'class_reference_name_casing' => true,
        'clean_namespace' => true,
        'combine_consecutive_issets' => true,
        'combine_consecutive_unsets' => true,
        'combine_nested_dirname' => true,
        'comment_to_phpdoc' => false,
        'compact_nullable_type_declaration' => true,
        'concat_space' => ['spacing' => 'one'],
        'constant_case' => ['case' => 'lower'],
        'control_structure_braces' => true,
        'control_structure_continuation_position' => ['position' => 'same_line'],
        'date_time_create_from_format_call' => false,
        'date_time_immutable' => false,
        'declare_equal_normalize' => ['space' => 'none'],
        'declare_parentheses' => true,
        'declare_strict_types' => false,
        'dir_constant' => true,
        'doctrine_annotation_array_assignment' => ['ignored_tags' => [], 'operator' => ':'],
        'doctrine_annotation_braces' => ['ignored_tags' => [], 'syntax' => 'without_braces'],
        'doctrine_annotation_indentation' => ['ignored_tags' => [], 'indent_mixed_lines' => false],
        'doctrine_annotation_spaces' => [
            'after_argument_assignments' => false,
            'after_array_assignments_colon' => true,
            'after_array_assignments_equals' => true,
            'around_commas' => true,
            'around_parentheses' => true,
            'before_argument_assignments' => false,
            'before_array_assignments_colon' => false,
            'before_array_assignments_equals' => false,
            'ignored_tags' => [],
        ],
        'echo_tag_syntax' => [
            'format' => 'long',
            'long_function' => 'echo',
            'shorten_simple_statements_only' => true,
        ],
        'elseif' => true,
        'empty_loop_body' => ['style' => 'braces'],
        'empty_loop_condition' => ['style' => 'while'],
        'encoding' => true,
        'ereg_to_preg' => true,
        'explicit_indirect_variable' => true,
        'explicit_string_variable' => false,
        'final_class' => false,
        'final_internal_class' => false,
        'final_public_method_for_abstract_class' => false,
        'fopen_flag_order' => true,
        'fopen_flags' => ['b_mode' => true],
        'full_opening_tag' => true,
        'fully_qualified_strict_types' => [
            'import_symbols' => false,
            'leading_backslash_in_global_namespace' => false,
            'phpdoc_tags' => [
                'param',
                'phpstan-param',
                'phpstan-property',
                'phpstan-property-read',
                'phpstan-property-write',
                'phpstan-return',
                'phpstan-var',
                'property',
                'property-read',
                'property-write',
                'psalm-param',
                'psalm-property',
                'psalm-property-read',
                'psalm-property-write',
                'psalm-return',
                'psalm-var',
                'return',
                'see',
                'throws',
            ],
        ],
        'function_declaration' => [
            'closure_fn_spacing' => 'none',
            'closure_function_spacing' => 'one',
            'trailing_comma_single_line' => false,
        ],
        'function_to_constant' => [
            'functions' => ['get_called_class', 'get_class', 'get_class_this', 'php_sapi_name', 'phpversion', 'pi'],
        ],
        'general_phpdoc_annotation_remove' => false,
        'general_phpdoc_tag_rename' => ['replacements' => ['inheritDocs' => 'inheritDoc']],
        'get_class_to_class_keyword' => true,
        'global_namespace_import' => [
            'import_classes' => true,
            'import_constants' => true,
            'import_functions' => true,
        ],
        'group_import' => false,
        'header_comment' => false,
        'heredoc_closing_marker' => false,
        'heredoc_indentation' => ['indentation' => 'start_plus_one'],
        'heredoc_to_nowdoc' => false,
        'implode_call' => true,
        'include' => true,
        'increment_style' => false,
        'indentation_type' => true,
        'integer_literal_case' => true,
        'is_null' => true,
        'lambda_not_used_import' => true,
        'line_ending' => true,
        'linebreak_after_opening_tag' => true,
        'list_syntax' => ['syntax' => 'short'],
        'logical_operators' => true,
        'long_to_shorthand_operator' => true,
        'lowercase_cast' => true,
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'mb_str_functions' => true,
        'method_argument_space' => [
            'after_heredoc' => true,
            'attribute_placement' => 'standalone',
            'keep_multiple_spaces_after_comma' => false,
            'on_multiline' => 'ensure_fully_multiline',
        ],
        'method_chaining_indentation' => true,
        'modernize_strpos' => true,
        'modernize_types_casting' => true,
        'multiline_comment_opening_closing' => true,
        'multiline_string_to_heredoc' => false,
        'multiline_whitespace_before_semicolons' => ['strategy' => 'no_multi_line'],
        'native_constant_invocation' => false,
        'native_function_casing' => true,
        'native_function_invocation' => false,
        'native_type_declaration_casing' => true,
        'new_with_parentheses' => [
            'anonymous_class' => false,
            'named_class' => true,
        ],
        'no_alias_functions' => ['sets' => ['@all']],
        'no_alias_language_construct_call' => true,
        'no_alternative_syntax' => true,
        'no_binary_string' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_break_comment' => ['comment_text' => 'no break'],
        'no_closing_tag' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => [
            'tokens' => [
                'attribute',
                'break',
                'case',
                'continue',
                'curly_brace_block',
                'default',
                'extra',
                'parenthesis_brace_block',
                'return',
                'square_brace_block',
                'switch',
                'throw',
                'use',
            ],
        ],
        'no_homoglyph_names' => false,
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_mixed_echo_print' => ['use' => 'echo'],
        'no_multiline_whitespace_around_double_arrow' => false,
        'no_multiple_statements_per_line' => true,
        'no_null_property_initialization' => false,
        'no_php4_constructor' => true,
        'no_short_bool_cast' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_space_around_double_colon' => true,
        'no_spaces_after_function_name' => true,
        'no_spaces_around_offset' => ['positions' => ['inside', 'outside']],
        'no_superfluous_elseif' => true,
        'no_trailing_comma_in_singleline' => [
            'elements' => [
                'arguments',
                'array_destructuring',
                'array',
                'group_import',
            ],
        ],
        'no_trailing_whitespace' => true,
        'no_trailing_whitespace_in_comment' => true,
        'no_trailing_whitespace_in_string' => false,
        'no_unneeded_braces' => ['namespaces' => false],
        'no_unneeded_control_parentheses' => [
            'statements' => ['break', 'clone', 'continue', 'echo_print', 'return', 'switch_case', 'yield'],
        ],
        'no_unneeded_final_method' => false,
        'no_unneeded_import_alias' => true,
        'no_unreachable_default_argument_value' => false,
        'no_unset_cast' => true,
        'no_unset_on_property' => false,
        'no_unused_imports' => true,
        'no_useless_concat_operator' => false,
        'no_useless_else' => true,
        'no_useless_nullsafe_operator' => false,
        'no_useless_return' => true,
        'no_useless_sprintf' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'non_printable_character' => true,
        'normalize_index_brace' => true,
        'not_operator_with_space' => false,
        'not_operator_with_successor_space' => true,
        'nullable_type_declaration' => ['syntax' => 'question_mark'],
        'nullable_type_declaration_for_default_null_value' => true,
        'object_operator_without_whitespace' => true,
        'octal_notation' => true,
        'operator_linebreak' => ['only_booleans' => false, 'position' => 'beginning'],
        'ordered_class_elements' => [
            'case_sensitive' => false,
            'order' => [
                'use_trait',
                'case',
                'constant_public',
                'constant_protected',
                'constant_private',
                'property_public_static',
                'property_protected_static',
                'property_private_static',
                'property_public',
                'property_protected',
                'property_private',
                'construct',
                'destruct',
                'method:__invoke',
                'phpunit',
                'method_public_static',
                'method_protected_static',
                'method_private_static',
                'method_public',
                'method_protected',
                'method_private',
                'magic',
            ],
            'sort_algorithm' => 'none',
        ],
        'ordered_imports' => [
            'case_sensitive' => false,
            'imports_order' => [
                'class',
                'function',
                'const',
            ],
            'sort_algorithm' => 'alpha',
        ],
        'ordered_interfaces' => ['case_sensitive' => false, 'direction' => 'ascend', 'order' => 'alpha'],
        'ordered_traits' => ['case_sensitive' => false],
        'ordered_types' => [
            'case_sensitive' => false,
            'null_adjustment' => 'always_first',
            'sort_algorithm' => 'alpha',
        ],
        'php_unit_construct' => false,
        'php_unit_data_provider_name' => false,
        'php_unit_data_provider_return_type' => false,
        'php_unit_data_provider_static' => false,
        'php_unit_dedicate_assert' => false,
        'php_unit_dedicate_assert_internal_type' => false,
        'php_unit_expectation' => false,
        'php_unit_fqcn_annotation' => true,
        'php_unit_internal_class' => true,
        'php_unit_method_casing' => ['case' => 'snake_case'],
        'php_unit_mock' => false,
        'php_unit_mock_short_will_return' => false,
        'php_unit_namespaced' => false,
        'php_unit_no_expectation_annotation' => false,
        'php_unit_set_up_tear_down_visibility' => false,
        'php_unit_size_class' => ['group' => 'small'],
        'php_unit_strict' => false,
        'php_unit_test_annotation' => false,
        'php_unit_test_case_static_method_calls' => false,
        'php_unit_test_class_requires_covers' => false,
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => true],
        'phpdoc_align' => [
            'align' => 'left',
            'spacing' => 1,
            'tags' => [
                'method',
                'param',
                'property',
                'return',
                'throws',
                'type',
                'var',
            ],
        ],
        'phpdoc_annotation_without_dot' => true,
        'phpdoc_indent' => true,
        'phpdoc_inline_tag_normalizer' => [
            'tags' => [
                'example',
                'id',
                'internal',
                'inheritdoc',
                'inheritdocs',
                'link',
                'source',
                'toc',
                'tutorial',
            ],
        ],
        'phpdoc_line_span' => ['const' => 'single', 'method' => 'multi', 'property' => 'single'],
        'phpdoc_no_access' => true,
        'phpdoc_no_alias_tag' => false,
        'phpdoc_no_empty_return' => false,
        'phpdoc_no_package' => false,
        'phpdoc_no_useless_inheritdoc' => true,
        'phpdoc_order' => ['order' => ['param', 'return', 'throws']],
        'phpdoc_order_by_value' => ['annotations' => ['covers', 'mixin', 'throws']],
        'phpdoc_param_order' => true,
        'phpdoc_return_self_reference' => [
            'replacements' => [
                'this' => '$this',
                '@this' => '$this',
                '$self' => 'self',
                '@self' => 'self',
                '$static' => 'static',
                '@static' => 'static',
            ],
        ],
        'phpdoc_scalar' => ['types' => ['boolean', 'callback', 'double', 'integer', 'real', 'str']],
        'phpdoc_separation' => [
            'groups' => [
                ['author', 'copyright', 'license'],
                ['category', 'package', 'subpackage'],
                ['custom'],
                ['property'],
                ['property-read'],
                ['property-write'],
                ['method'],
                ['param'],
                ['return'],
                ['throw'],
                ['deprecated', 'link', 'see', 'since'],
            ],
            'skip_unlisted_annotations' => true,
        ],
        'phpdoc_single_line_var_spacing' => true,
        'phpdoc_summary' => false,
        'phpdoc_tag_casing' => ['tags' => ['inheritDoc']],
        'phpdoc_tag_type' => [
            'tags' => [
                'api' => 'annotation',
                'author' => 'annotation',
                'copyright' => 'annotation',
                'deprecated' => 'annotation',
                'example' => 'annotation',
                'global' => 'annotation',
                'inheritDoc' => 'annotation',
                'internal' => 'annotation',
                'license' => 'annotation',
                'method' => 'annotation',
                'package' => 'annotation',
                'param' => 'annotation',
                'property' => 'annotation',
                'return' => 'annotation',
                'see' => 'annotation',
                'since' => 'annotation',
                'throws' => 'annotation',
                'todo' => 'annotation',
                'uses' => 'annotation',
                'var' => 'annotation',
                'version' => 'annotation',
            ],
        ],
        'phpdoc_to_comment' => false,
        'phpdoc_trim' => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types' => ['groups' => ['simple', 'alias', 'meta']],
        'phpdoc_types_order' => [
            'case_sensitive' => false,
            'null_adjustment' => 'always_first',
            'sort_algorithm' => 'alpha',
        ],
        'phpdoc_var_annotation_correct_order' => true,
        'phpdoc_var_without_name' => true,
        'pow_to_exponentiation' => true,
        'protected_to_private' => false,
        'psr_autoloading' => ['dir' => __DIR__.'/app'],
        'random_api_migration' => [
            'replacements' => ['getrandmax' => 'mt_getrandmax', 'rand' => 'mt_rand', 'srand' => 'mt_srand'],
        ],
        'regular_callable_call' => false,
        'return_assignment' => true,
        'return_to_yield_from' => false,
        'return_type_declaration' => ['space_before' => 'none'],
        'self_accessor' => false,
        'self_static_accessor' => false,
        'semicolon_after_instruction' => true,
        'set_type_to_cast' => false,
        'short_scalar_cast' => true,
        'simple_to_complex_string_variable' => true,
        'simplified_if_return' => true,
        'simplified_null_return' => true,
        'single_blank_line_at_eof' => true,
        'single_class_element_per_statement' => ['elements' => ['const', 'property']],
        'single_import_per_statement' => ['group_to_single_imports' => true],
        'single_line_after_imports' => true,
        'single_line_comment_spacing' => true,
        'single_line_comment_style' => ['comment_types' => ['asterisk', 'hash']],
        'single_line_empty_body' => true,
        'single_line_throw' => true,
        'single_quote' => ['strings_containing_single_quote_chars' => false],
        'single_space_around_construct' => true,
        'single_trait_insert_per_statement' => true,
        'space_after_semicolon' => true,
        'spaces_inside_parentheses' => ['space' => 'none'],
        'standardize_increment' => true,
        'standardize_not_equals' => true,
        'statement_indentation' => [
            'stick_comment_to_next_continuous_control_statement' => false,
        ],
        'static_lambda' => false,
        'strict_comparison' => true,
        'strict_param' => false,
        'string_implicit_backslashes' => [
            'double_quoted' => 'ignore',
            'heredoc' => 'ignore',
            'single_quoted' => 'ignore',
        ],
        'string_length_to_empty' => false,
        'string_line_ending' => false,
        'switch_case_semicolon_to_colon' => true,
        'switch_case_space' => true,
        'switch_continue_to_break' => true,
        'ternary_operator_spaces' => true,
        'ternary_to_elvis_operator' => false,
        'ternary_to_null_coalescing' => true,
        'trailing_comma_in_multiline' => [
            'after_heredoc' => false,
            'elements' => ['arguments', 'arrays', 'match', 'parameters'],
        ],
        'trim_array_spaces' => true,
        'type_declaration_spaces' => ['elements' => ['function', 'property']],
        'types_spaces' => ['space' => 'none', 'space_multiple_catch' => null],
        'unary_operator_spaces' => [
            'only_dec_inc' => true,
        ],
        'use_arrow_functions' => false,
        'visibility_required' => ['elements' => ['property', 'method', 'const']],
        'void_return' => false,
        'whitespace_after_comma_in_array' => ['ensure_single_space' => true],
        'yield_from_array_to_yields' => false,
        'yoda_style' => false,
    ]);
