version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    container_name: bookhub-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      - PHP_ENABLE_XDEBUG=1
    networks:
      - bookhub-network

  db:
    image: mariadb:10.11
    container_name: bookhub-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookhub
      MYSQL_USER: bookhub_user
      MYSQL_PASSWORD: bookhub_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bookhub-network

volumes:
  db_data:

networks:
  bookhub-network:
    driver: bridge
